include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/pub/**
    - lib/l10n/**
    - lib/generated/**
    - '**.freezed.dart'
    - '**.g.dart'

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    todo: ignore

linter:
  rules:
    # rules to enable
    prefer_single_quotes: true
    always_declare_return_types: true
    always_use_package_imports: true

    # rules to disable
    sort_pub_dependencies: false